### ISSUE TITLE
Use `FilePath` instead of `ByteString`?

### ISSUE THREAD

**Issue by lpeterse** [VyacheslavHashov/haskell-socket-unix#1]
I already thought about this a while ago and asked myself whether it should be `ByteString` or `System.IO.FilePath` within `SocketAddress Unix`.

The latter would be more consistent with the rest of the Haskell world and would allow to use the `filepath` library for path manipulation. Encoding issues may arise on the other hand though.

**Comment by VyacheslavHashov** [comment]
On Unix and Linux systems filepath is a sequence of raw bytes terminated by NUL. This library http://hackage.haskell.org/package/unix-2.7.2.0/docs/System-Posix-ByteString.html defines it as
`type RawFilePath = ByteString` 
and allows POSIX-compatible path manipulation already.
