### ISSUE TITLE
`ProtocolNumber = Unix`

### ISSUE THREAD

**Issue by lpeterse** [VyacheslavHashov/haskell-socket-unix#2]
I was preparing a new version (branch `0.8.x.x`) of socket, but got a little stuck and overengineered. 

Long story short: It contains a `Default` type which is instance of `Protocol` which has protocol number 0. You might not need the additional `UnixProtocol` then (but maybe it still makes sense?).

I will try to finally get it released tomorrow or the day after.

**Comment by VyacheslavHashov** [comment]
Protocol parameter in the `socket` function does not make sense in the case of Unix sockets and should be always 0. At first, I even started writing you issue about adding Default, but then noticed that it presents in 0.8 branch. So, `ProtocolNumber = Unix` is temporary solution.

**Comment by VyacheslavHashov** [comment]
Done, f5e59407bfd5a7f4125a93c9e1fe6a5ba6756afc
